name: MSC Gemi Takip Otomatik Kontrol Servisi

on:
  schedule:
    # Her 15 dakikada bir otomatik çalışır
    - cron: '*/15 * * * *'
  workflow_dispatch: # İstenirse elle de tetikleme butonu oluşturur

jobs:
  check-ships-job:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v4

      - name: Node.js Kurulumu
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Kontrol Kodunu Çalıştır
        run: node check-ships.js
